import { useEffect, useMemo, useState } from 'react'
import { Button, Input, message } from 'antd'
import { Clock3, Clipboard, Download, RotateCcw } from 'lucide-react'
import { SplitWorkspace } from '../../shared/components/SplitWorkspace.jsx'
import { useToolActions } from '../../shared/components/ToolChromeContext.jsx'
import { copyText } from '../../shared/utils/clipboard.js'
import { downloadTextFile } from '../../shared/utils/download.js'
import { loadDraft, saveDraft } from '../../shared/utils/localDraft.js'
import { cronExpressionExample } from './example.js'
import './style.css'
const toolId = 'cron-expression-helper'
const dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
function parseField(field, min, max) { const values = new Set(); for (const part of field.split(',')) { if (part === '*') { for (let i=min;i<=max;i++) values.add(i) } else if (part.startsWith('*/')) { const step=Number(part.slice(2)); for (let i=min;i<=max;i+=step) values.add(i) } else if (part.includes('-')) { const [a,b]=part.split('-').map(Number); for (let i=a;i<=b;i++) values.add(i) } else values.add(Number(part)) } return [...values].filter((n)=>Number.isInteger(n)&&n>=min&&n<=max).sort((a,b)=>a-b) }
function explain(expr) { const [min,hour,dom,mon,dow]=expr.trim().split(/\s+/); if (!dow) throw new Error('Cron must have 5 fields'); const minutes=parseField(min,0,59), hours=parseField(hour,0,23), days=parseField(dow,0,6); return { minutes, hours, dom: parseField(dom,1,31), mon: parseField(mon,1,12), days, summary: [`Every ${min.startsWith('*/') ? min.slice(2) : 'selected'} minutes`, `${String(hours[0]).padStart(2,'0')}:00 through ${String(hours.at(-1)).padStart(2,'0')}:59`, days.length===5&&days[0]===1&&days[4]===5 ? 'Monday through Friday' : days.map((d)=>dayNames[d]).join(', ')] } }
function nextRuns(parsed) { const runs=[]; const d=new Date(); d.setSeconds(0,0); d.setMinutes(d.getMinutes()+1); for (let i=0;i<525600&&runs.length<10;i++) { if (parsed.minutes.includes(d.getMinutes())&&parsed.hours.includes(d.getHours())&&parsed.days.includes(d.getDay())&&parsed.dom.includes(d.getDate())&&parsed.mon.includes(d.getMonth()+1)) runs.push(new Date(d)); d.setMinutes(d.getMinutes()+1) } return runs }
function calculate(expr) { try { const parsed=explain(expr); return { ...parsed, runs: nextRuns(parsed), error: '' } } catch (error) { return { summary: [], runs: [], error: error.message } } }
export default function CronExpressionHelperTool() { const [expr,setExpr]=useState(()=>loadDraft(toolId,cronExpressionExample)); const [result,setResult]=useState(()=>calculate(expr)); useEffect(()=>saveDraft(toolId,expr),[expr]); const run=()=>setResult(calculate(expr)); const output=[...result.summary, ...result.runs.map((d)=>d.toLocaleString())].join('\n'); const copy=async()=>{const res=await copyText(output); message[res.ok?'success':'warning'](res.message)}; const reset=()=>{setExpr(cronExpressionExample); setResult(calculate(cronExpressionExample))}; const actions=useMemo(()=><><Button icon={<Clock3 size={16}/>} type="primary" onClick={run}>Explain Cron</Button><Button icon={<Clipboard size={16}/>} onClick={copy}>Copy</Button><Button icon={<Download size={16}/>} onClick={()=>downloadTextFile(output,'cron-runs.txt')}>Download</Button><Button icon={<RotateCcw size={16}/>} onClick={reset}>Example</Button></>,[expr,result]); useToolActions(actions); return <div className="tool-page developer-tool-page"><SplitWorkspace leftToolbar={<><label className="tool-function-label" htmlFor="cron-expression">Cron expression</label><Input id="cron-expression" aria-label="Cron expression" value={expr} onChange={(e)=>setExpr(e.target.value)} /></>} left={<div className="dev-result"><div className="dev-card"><h3>Supported syntax</h3><p>Five fields: minute hour day month weekday. Supports *, */step, ranges, and lists.</p></div></div>} right={<div className="dev-result">{result.error ? <div className="dev-card">{result.error}</div> : <><div className="dev-card"><h3>Summary</h3>{result.summary.map((line)=><p key={line}>{line}</p>)}</div><div className="dev-card"><h3>Next Runs</h3><ul className="dev-list" data-testid="cron-next-runs">{result.runs.map((d)=><li key={d.toISOString()}>{d.toLocaleString()}</li>)}</ul></div></>}</div>} /></div> }
